# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: CI - Demo

on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./demo/with-cra

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Lint check
        run: yarn lint

      - name: Type check
        run: yarn type-check
