# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: CI

on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint check
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Unit test
        run: npm run test
        
      - name: Test Coverage
        run: test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.0.3
        with:
          files: ./coverage/coverage-final.json
          fail_ci_if_error: true
          name: codecov-umbrella
          verbose: true